# Generated by Django 3.0.3 on 2020-06-28 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcctv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='people',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.IntegerField()),
                ('up', models.IntegerField()),
                ('down', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
