# Generated by Django 3.0.3 on 2020-06-28 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcctv', '0002_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='date',
            field=models.CharField(max_length=100),
        ),
    ]
