# Generated by Django 3.0.3 on 2020-06-28 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcctv', '0003_auto_20200628_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='cid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='people',
            name='down',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='people',
            name='up',
            field=models.IntegerField(default=0),
        ),
    ]
