# Generated by Django 3.0.3 on 2020-07-30 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcctv', '0004_auto_20200628_0827'),
    ]

    operations = [
        migrations.CreateModel(
            name='detect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('did', models.IntegerField(default=0)),
                ('detect_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='heatmap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hid', models.IntegerField(default=0)),
                ('best', models.IntegerField(default=0)),
                ('worst', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='cctv',
            old_name='emial',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='people',
            name='date',
        ),
    ]
