# Generated by Django 3.0.3 on 2020-08-10 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartcctv', '0006_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
