# Generated by Django 3.0.3 on 2020-08-16 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcctv', '0007_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartcctvPeople',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.IntegerField()),
                ('up', models.IntegerField()),
                ('down', models.IntegerField()),
            ],
            options={
                'db_table': 'smartcctv_people',
                'managed': False,
            },
        ),
    ]
