# Generated by Django 3.0.3 on 2020-09-08 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartcctv', '0008_smartcctvpeople'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='smartcctvpeople',
            table='people_count',
        ),
    ]
