# Generated by Django 3.0.3 on 2020-09-29 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcctv', '0010_auto_20200908_0818'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.IntegerField()),
                ('username', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Camera',
                'managed': False,
            },
        ),
    ]
